### ISSUE TITLE
vite-plugin-ts提个问题

### ISSUE THREAD

**Issue by agileago** [CarterLi/download-kernel#5]
发现用 tsc直接命令行编译的结果和用 transpileModule编译出来的不一样，你知道为什么么？

例子： https://stackblitz.com/edit/node-pxkjqk?file=index.js

主要区别是 元数据的类型不一样， 参数的类型会被编译为
```typescript
typeof (_a = typeof InstanceType !== 'undefined' && InstanceType) ===
      'function'
        ? _a
        : Object,
``

**Comment by agileago** [comment]
找到原因了， https://github.com/microsoft/TypeScript/issues/18008

**Comment by agileago** [comment]
transpile模式下确实会和命令行不一样

**Comment by CarterLi** [comment]
vite-plugin-ts这插件居然真有人用😂

**Comment by agileago** [comment]
咋了，我需要用到装饰器做依赖注入，搜了一下就用了

**Comment by CarterLi** [comment]
挺好啊

至于类型的问题，transpileModule只能看到当前文件的内容，获得的信息有限。而tsc针对的是整个项目，获得的信息更全面。我估计是这个原因导致的差异。

既然问题解决了，issue我关了

**Comment by agileago** [comment]
@CarterLi 是否也可以像 `ts-loader` 那样提供一个 https://github.com/TypeStrong/ts-loader#transpileonly  `transpileonly` 的选项使这个问题缓解

**Comment by CarterLi** [comment]
我研究了一下，transpileonly不是一个简单的开关，ts-loader对于是否开启transpileonly使用了完全不同的逻辑

https://github.com/TypeStrong/ts-loader/blob/55d2a85850674d69af1be603c1218384465fa457/src/index.ts#L77

然后这逻辑我看不懂。。。你有兴趣研究的话可以开PR @agileago

**Comment by agileago** [comment]
先把项目迁移到 vue-cli 吧， vite后期看看有空再搞
